s = "welcome to Python"
print(s)
print(s[0])
print(s[::-1])
print(s[0:7:2])
s2 = s.replace("Python", "Java")
print(s2)
print(id(s))
print(id(s2))
print(s.count("o"))
print(s.find("o"))
s3 = s + " " + s2
print(s3)
print(s3.split(" "))
print(s3.upper())
print(s3.lower())
print(s3.title())
print(s3.capitalize())
print(s3.swapcase())
print(s3.islower())
print(s3.isupper())
print(s3.isalpha())
print(s3.isalnum())
print(s3.isdecimal())
print(s3.isdigit())
print(s3.isnumeric())
print(s3.isspace())
print(s3.istitle())
print(s3.startswith("welcome"))
print(s3.endswith("Java"))
print(s3.strip())
print(s3.rstrip())
print(s3.lstrip())
print(s3.center(100))
print(s3.ljust(100))
print(s3.rjust(100))
